# Site settings
title_left: "rhiroyuki's"
title_right: " blog" # default: ""
description: "Blog where I make posts about random things and tech stuff."
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist"
url: "https://rhiroyuki.github.io" # site url
baseurl: "/blog" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover: "" # image uri like logo/cover image for site seo

google_analytics: UA-XXXXX-XX
twitter_username: "richiroyuki"
comments_enabled: true # if enabled (set to true), please provide your disqus_username
disqus_shortname: "rhiroyuki-github-io"
postshare_enabled: false

# Build settings
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name: "Ricardo Eihara"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "script"]
