version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.5.3-node-browsers

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "4d:d6:26:6e:bf:86:01:e7:ec:d4:f8:8e:3b:83:34:33"
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run: bundle exec jekyll build

      - deploy:
          name: Deployment to Github
          command: |
            if [ $CIRCLE_BRANCH == 'develop' ]; then
              chmod +x .circleci/scripts/gh-deploy.sh
              bash .circleci/scripts/gh-deploy.sh
            fi
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: develop
